# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
name: install_aws_tools_ps_$(Date:yyyyMMdd)$(Rev:.r)
variables:
  - group: app-one
  - name: region
    value: 'us-east-2'
  - name: profile
    value: 'PSProfile'
trigger:
  branches:
    include:
      - main
  paths:
    include:
      - install-aws-tools-powershell
pr:
  - main
pool:
    vmImage: ubuntu-latest
  
steps:
  - task: PowerShell@2
    displayName: 'Check and install AWS.Tools.Installer and AWS.Tools.Common modules'
    inputs:
      filePath: '$(build.sourcesdirectory)/install-aws-tools-powershell/InstallAWSTools.ps1'
  - task: PowerShell@2
    displayName: 'Set AWS Credential'
    inputs:
      targetType: 'inline'
      script: 'Set-AWSCredential -AccessKey $(access_key) `
                -SecretKey $(secret_key) `
                -StoreAs $(profile)'

  - task: PowerShell@2
    displayName: 'Remove AWS Credential'
    inputs:
      targetType: 'inline'
      script: 'Remove-AWSCredentialProfile -ProfileName $(profile) -Force'
    condition: always()