# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
variables:
  - group: app-one
  - name: region
    value: 'us-east-2'
  - name: profile
    value: 'PSProfile'
trigger:
  - install-awstools
  
pool:
    vmImage: ubuntu-latest
  
steps:
  - task: PowerShell@2
    displayName: 'Check and install AWS.Tools.Installer and AWS.Tools.Common modules'
    inputs:
      filePath: '$(build.sourcesdirectory)/install-aws-tools-powershell/InstallAWSTools.ps1'
  - task: PowerShell@2
    displayName: 'Set AWS Credentail'
    inputs:
      targetType: 'inline'
      script: 'Set-AWSCredential -AccessKey $(access_key) `
                -SecretKey $(secret_key) `
                -StoreAs $(profile)'
  - task: PowerShell@2
    displayName: 'Run region test'
    inputs:
      filePath: '$(build.sourcesdirectory)/install-aws-tools-powershell/regiontest.ps1'
  - task: PowerShell@2
    displayName: 'Set AWS DefaultRegion'
    inputs:
      targetType: 'inline'
      script: |
        Set-DefaultAWSRegion -Region $(region) `
        $RegionValue = Get-DefaultAWSRegion
        Write-Host "Value of AWS DefaultRegion: $(RegionValue)"
  # - task: PowerShell@2
  #   displayName: 'Get AWS DefaultRegion'
  #   inputs:
  #     targetType: 'inline'
  #     script: 'Write-Host "Value of AWS DefaultRegion: $StoredAWSRegion"'
  #   continueOnError: true