# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
variables:
  - group: demo-one

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - azure-devops-library-variable-group
pr:
  - main
pool:
    vmImage: ubuntu-latest
  
steps:
  - task: PowerShell@2
    displayName: 'Display variable values'
    inputs:
      targetType: 'inline'
      script: 'Write-Host "Value of secure variable: `
      $(SecureVariable)" `n"Value of unsecure variable: `
      $(UnsecureVariable)"'
