# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  # branches:
  #   include:
  #     - main
  paths:
    include:
    - tools-version-check
  
pool:
    vmImage: ubuntu-latest
  
steps:
  - task: PowerShell@2
    displayName: 'check eksctl version'
    inputs:
      targetType: 'inline'
      script: 'eksctl -version'
