# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "add-aws-credentials-to-gh-actions" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  bucket_name: kunduso-terraform-remote-bucket-1234567
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials Action For GitHub Actions
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: ${{ secrets.IAM_ROLE }}
          role-session-name: AWSSession
          aws-region: us-east-2
      # Runs a command to interact with aws cloud
      - name: Check if bucket exists and delete it
        run: |
          if aws s3api head-bucket --bucket "$bucket_name" 2>/dev/null;
          then
            echo "bucket found and deleting the bucket"
            aws s3 rb s3://"$bucket_name" --force
          else
            echo "no bucket found"
          fi
      - name: Create the bucket that was deleted
        run: |
          echo "creating bucket"
          aws s3 mb s3://"$bucket_name"

